// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleRepository.Sql;

namespace PeopleRepository.Sql.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview9.19423.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleRepository.Sql.PersonDto", b =>
                {
                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LastName");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            LastName = "Elmer",
                            FirstName = "John",
                            Rating = 6,
                            StartDate = new DateTime(1975, 10, 17, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Hunt",
                            FirstName = "Francis",
                            Rating = 7,
                            StartDate = new DateTime(2000, 2, 6, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Montana",
                            FirstName = "Amanda",
                            Rating = 6,
                            StartDate = new DateTime(1999, 8, 25, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Sheridan",
                            FirstName = "Steven",
                            Rating = 8,
                            StartDate = new DateTime(1991, 11, 11, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Gampu",
                            FirstName = "Eleanor",
                            Rating = 5,
                            StartDate = new DateTime(1996, 12, 9, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Koenig",
                            FirstName = "Paul",
                            Rating = 9,
                            StartDate = new DateTime(1981, 4, 20, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Lister",
                            FirstName = "Gabriela",
                            Rating = 4,
                            StartDate = new DateTime(1984, 4, 19, 22, 20, 29, 55, DateTimeKind.Utc)
                        },
                        new
                        {
                            LastName = "Stephens",
                            FirstName = "Petra",
                            Rating = 9,
                            StartDate = new DateTime(2005, 2, 10, 22, 20, 29, 55, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
